# Generated by Django 4.2.2 on 2023-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calorie',
            field=models.FloatField(default=0),
        ),
    ]
